---
title: "Item response Theory"
---

```{r packages, include=FALSE}
# Checks if package is installed, installs if necessary, and loads package for current session
Sys.setenv(tz="GMT")

pacman::p_load(
  RColorBrewer,
  ggthemes,
  sjPlot,
  lubridate,  # general package for handling and converting dates  
  linelist,   # has function to "guess" messy dates
  aweek,      # another option for converting dates to weeks, and weeks to dates
  zoo,        # additional date/time functions
  tidyverse,  # data management and visualization  
  rio,
  magrittr,
  gtsummary,
  flextable,
  ggthemes,
  ggThemeAssist,
  tidylog,
  epitools,
  usethis,
  mirt)        # data import/export
```

<br>


```{r cool_tips, eval=FALSE, include=FALSE}
#library(haven)
itr <- haven::read_dta("C:/Users/hp/Downloads/Health Workers_Dataset.dta")

```

```{r data, include=FALSE}
saveRDS(itr, "itr.RDS")

itr<-readRDS("itr.RDS")

itr%<>%
  mutate(id=c(1:157), .before=start)
```


```{r mirt, include=FALSE}
plan<-itr%>%
  select(c(1,159:162,164:171,173,175:176,178))%>%
  select(!starts_with("other"))%>%
  #filter(!id %in% c(71,89)) %>%
  replace_na(list(conducting_review=5, review_meetings=3, exclusive_microplanning=3,
                  facilitators=4, supervisory_visit=4, How_review_progress =4,district_activity_plan=3,resolve_issues_community=3,develop_socialmap=3,
                  operational_map=3))

haven::write_dta(plan,"plan.dta")

Rea<-itr%>%
  select(c(1,180:201))%>%
  select(!starts_with("other"))%>%
  #select_if(is.numeric)#%>%
  #select(-c(specify_othermonitoringofimmuniz))
  #filter(!id %in% c(71,89)) %>%
  replace_na(list(freq_review_microplan=4, immunization_session=3, 
                  past_36months_review=5,
                  support_community_leaders=4, regularmeetings_communityleaders=4, What_microplan =3,
          
             get_reviewed =3,immunizationsessions_per_month=5,monitor_efficiency_immunizatio=4,
  challenges_community=4,additional_opportunity_coverage=5,
  conduct_monitor_immunizationsess=3
                  ))

bi_rea<-Rea%>%
  mutate(across(c(2:13),try))

bi_rea$total_bi_rea<-rowSums(bi_rea[,2:13])
  
com_eng<-itr%>%
  select(c(1,204:224))%>%
  select(!starts_with("other"))%>%
  select(!starts_with("specify"))%>%
  replace_na(list(community_engagement=3, building_community_participation=3,
             right_to_vaccination=3, identify_community_structure=3,
             trusted_friendly_service=3,engage_with_community=3,
             effective_communication_channel=5,community_register=3,
             communication_in_immunization=4, conducting_meeting=3, 
             component_community_engagement=3))

bi_com_eng<-com_eng%>%
   mutate(across(c(2:12),try))

bi_p%<>%
  mutate(total_bi_p=rowSums(bi_p[,2:11]))

superv<-itr%>%
  select(c(1,226:238))%>%   #240:253
  select(!starts_with("other"))%>%
  select(!starts_with("specify"))%>%
  replace_na(list(What_supportive_supervision=3, plan_for_supportivesupervision=3,
              supervision_specific_to1or2=4, prepare_for_supervision=3,
             effective_supervision=3,plan_visit=3,
             supportive_supervisory_visit=4))


bi_superv<-superv%>%
  mutate(across(c(2:8),try))
bi_superv%<>%
  mutate(total_bi_superv=rowSums(bi_superv[,2:8]))

monitor<-itr%>%
  select(c(1,240:253))%>%
  select(!starts_with("other"))%>%
  select(!starts_with("specify"))%>%
 select_if(is.numeric)%>%
  replace_na(list(process_for_action=3,process_indicators=4, performance_indicators=3,effective_immunization=3,update_microplan=3,strategy_integrated=3))

summary(is.na(monitor))

bi_monitor<-monitor%>%
  mutate(across(c(2:7),try))
bi_monitor%<>%
  mutate(total_bi_monitor=rowSums(bi_monitor[,2:7]))

ifa=bind_cols(bi_p,bi_rea,bi_com_eng,bi_superv,bi_monitor)

ifa%<>%select(-c(13,27,40,49))%>%rename(
  reg_meet_com_leaders=regularmeetings_communityleaders,
  conduct_monitor_immuniz=conduct_monitor_immunizationsess,
  build_comm_participn=building_community_participation
)%>%
  mutate(plan_mg_100=round((total_bi_p/10)*100),
         rea_100=round((total_bi_rea/12)*100),
         com_eng_100=round((total_bi_com_eng/11)*100),
         superv_100=round((total_bi_superv/7)*100),
         monitor_100=round((total_bi_monitor/6)*100),
         total_REC=round(((plan_mg_100+rea_100+com_eng_100+superv_100+monitor_100)/500)*100))

names(ifa)<-gsub("-|\\.|\\/|'|\\[|\\]","", names(ifa))
names(ifa)<-gsub(" ","_", names(ifa))
haven::write_dta(ifa,"ifa.dta")

facilities<-merge(ifa,itr[,1,6])

haven::write_dta(facilities,"facilities.dta")

#summary(ifa$plan_mg_100,ifa$rea_100, ifa$com_eng_100, ifa$superv_100, ifa$monitor_100)
summary(ifa[,53:58])



bi_com_eng%<>%
  mutate(total_bi_com_eng=rowSums(bi_com_eng[,2:12]))
  
 mutate(across(c(2:11),try))
#%>%
  select_if(is.numeric)#%>%
summary(is.na(Rea))  
  
summary(is.na(com_eng))
#itr%<>%mutate(
  itr$additional_opportunity_coverage<-
    if_else(itr$additional_opportunity_coverage=="Child Health Day",2,as.numeric(itr$additional_opportunity_coverage))


itr$additional_opportunity_coverage<-
  replace(itr$additional_opportunity_coverage,"Child Health Day",2)


#subst%<>%
  #mutate(total=sum(bi_p))


  
rep=function(x){
  replace_na(max(x))
}
bi_p<-plan%>%
  mutate(across(c(2:11),try))

p=ltm(bi_p~z1)
 
factor.scores(p)               
                
try=function(x){
  if_else(x==1,1,0)}


summary(plan)

summary(is.na(plan))
summary(mod_p2)
mod_p<-mirt::mirt(plan,1)


mod_p1<-mirt::mirt(plan,1, itemtype = "Rasch")
mod_p2<-mirt::mirt(bi_p[,2:11],1)

fscores(mod_p2)
mop<-gpcm(plan)
factor.scores.gpcm(mop)
coef(mod_p)
summary(mod_p)

coef(mod_p2)
fscores(mod_p)
fscores(mod_p1)

u=bind_cols(id=bi_p$id,bi=fscores(mod_p2),
      total=rowSums(bi_p))


saveRDS(u,"u.RDS")

bi_p
haven::write_dta(bi_p,"plan_dichotomous.dta")

plot(mod_p1, type = 'trace') #trace lines
plot(mod_p, type = 'info')

plot(mod_p, type = c('ICC'))


results=tibble(name=c("plan_mg", "reach_eli_pop","community_engage","supervision","monitoring","total_REC"),
               mean=round(c(mean(ifa$plan_mg_100),mean(ifa$rea_100),mean(ifa$com_eng_100),mean(ifa$superv_100),
                      mean(ifa$monitor_100),mean(ifa$total_REC))))
print(flextable(results),"docx")
```


```{r data2, include=FALSE}
subst<-itr%>%
  select(c(1,157:315))%>%
  mutate(across(c(1:50),as_factor))


plan_mg<-itr%>%
  select(c(1,159:178))%>%
  select(!starts_with("other"))%>%
  mutate(across(c(2:15),as_factor))%>%
  filter(!id %in% c(71,89))  #removing row 71, 89

#%>%
  mutate(orientation_in_REDapproach=if_else(orientation_in_REDapproach==" ","No idea",
                                            orientation_in_REDapproach))


  mutate(orientation_in_REDapproach=if_else(orientation_in_REDapproach==" ","No idea",
                                            orientation_in_REDapproach),
         reviewmeetings_monitor_progress==" ","No idea",reviewmeetings_monitor_progress,          key_indicators_monitoring==" ","No idea",key_indicators_monitoring)

plan%<>%
  mutate(orientation_in_REDapproach=if_else(orientation_in_REDapproach=="No idear","No idea",
                                            orientation_in_REDapproach),
         reviewmeetings_monitor_progress==" ","No idea",reviewmeetings_monitor_progress,          key_indicators_monitoring==" ","No idea",key_indicators_monitoring)



expand.table(plan)

which(is.na(plan_mg),arr.ind = T)

summary(plan_mg)
```
